#! /usr/bin/env python

import rospy
import actionlib
import sys

from fprime_msgs.msg import RunSeqAction, RunSeqGoal

if __name__ == '__main__':
   if len(sys.argv) < 2:
      sys.exit(1)

   rospy.init_node('run_seq_client')
   client = actionlib.SimpleActionClient('ROSSEQ', RunSeqAction)
   client.wait_for_server()

   goal = RunSeqGoal()
   goal.pathToSeq.data = sys.argv[1]
   client.send_goal(goal)
   client.wait_for_result()
